// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestTask.MaternityHospital.StorageService.Persistence;

#nullable disable

namespace TestTask.MaternityHospital.StorageService.Persistence.Migrations
{
    [DbContext(typeof(PatientsDbContext))]
    [Migration("20250729162349_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TestTask.MaternityHospital.StorageService.Interfaces.Patients.Models.PatientDataModel", b =>
                {
                    b.Property<string>("PatientGlobalKey")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("BirthDateTimeUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Family")
                        .HasColumnType("longtext");

                    b.Property<string>("Gender")
                        .HasColumnType("longtext");

                    b.Property<string>("GivenFirst")
                        .HasColumnType("longtext");

                    b.Property<string>("GivenSecond")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Use")
                        .HasColumnType("longtext");

                    b.HasKey("PatientGlobalKey");

                    b.ToTable("Patients");
                });
#pragma warning restore 612, 618
        }
    }
}
